name: ci-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Conan
        run: pip install conan

      - name: Conan Profile Setup
        run: |
          conan profile detect
          conan install . --output-folder=build --build=missing
        shell: bash

      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -G "Ninja"

      - name: Build Project
        run: cmake --build build

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure
